from nirv import short

CORPUS = short
BATCH_SIZE = 60
MAX_GENERATION_SIZE = 20
KL_TRANSLATE = 25000
KL_PARAM = 0.001
CHECKPOINT_FILE = 'output/temp.ckpt'
TRAIN_DIR = 'train'
TB_LOGS_DIR = 'tb_logs'
NUM_EPOCHS = 75
TRAIN_RATIO = 0.7
VALIDATION_RATIO = 0.15
TEST_RATIO = 0.15

RANDOM_SEED=1234