BATCH_SIZE = 60
MAX_GENERATION_SIZE = 30
KL_TRANSLATE = 30
KL_PARAM = 5
CHECKPOINT_FILE = 'output/temp.ckpt'
TB_LOGS_DIR = 'tb_logs'
NUM_EPOCHS = 100
TRAIN_RATIO = 0.7
VALIDATION_RATIO = 0.15
TEST_RATIO = 0.15
STYLE_FRACTION = .01

RANDOM_SEED=1234
